python -u main_informer.py --model informer --gpu 1 --data ETTh1 --attn prob --save_file etth1.24.txt --freq h --pred_len 24
python -u main_informer.py --model informer --gpu 1 --data ETTh1 --attn prob --save_file etth1.48.txt --freq h --pred_len 48
python -u main_informer.py --model informer --gpu 1 --data ETTh1 --attn prob --save_file etth1.168.txt --freq h --pred_len 168
python -u main_informer.py --model informer --gpu 1 --data ETTh1 --attn prob --save_file etth1.336.txt --freq h --pred_len 336
python -u main_informer.py --model informer --gpu 1 --data ETTh1 --attn prob --save_file etth1.720.txt --freq h --pred_len 720
python -u main_informer.py --model informer --gpu 1 --data ETTh2 --attn prob --save_file etth2.24.txt --freq h --pred_len 24
python -u main_informer.py --model informer --gpu 1 --data ETTh2 --attn prob --save_file etth2.48.txt --freq h --pred_len 48
python -u main_informer.py --model informer --gpu 1 --data ETTh2 --attn prob --save_file etth2.168.txt --freq h --pred_len 168
python -u main_informer.py --model informer --gpu 1 --data ETTh2 --attn prob --save_file etth2.336.txt --freq h --pred_len 336
python -u main_informer.py --model informer --gpu 1 --data ETTh2 --attn prob --save_file etth2.720.txt --freq h --pred_len 720
python -u main_informer.py --model informer --gpu 1 --data ETTm1 --attn prob --save_file ettm1.24.txt --freq h --pred_len 24
python -u main_informer.py --model informer --gpu 1 --data ETTm1 --attn prob --save_file ettm1.48.txt --freq h --pred_len 48
python -u main_informer.py --model informer --gpu 1 --data ETTm1 --attn prob --save_file ettm1.96.txt --freq h --pred_len 96
python -u main_informer.py --model informer --gpu 1 --data ETTm1 --attn prob --save_file ettm1.288.txt --freq h --pred_len 288
python -u main_informer.py --model informer --gpu 1 --data ETTm1 --attn prob --save_file ettm1.672.txt --freq h --pred_len 672
